import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Temp.module.css";

const Temp: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          Get started by editing
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Documentation &rarr;</h2>
          </a>

          <a href="#" className={styles.card}>
            <h2>Learn &rarr;</h2>
          </a>

          <a href="#" className={styles.card}>
            <h2>Examples &rarr;</h2>
          </a>

          <a href="#" className={styles.card}>
            <h2>Deploy &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Temp;
